language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t benraa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benraa/react-test npm run test

after_success:
  - docker build -t benraa/multi-client ./client
  - docker build -t benraa/multi-nginx ./nginx
  - docker build -t benraa/multi-server ./server
  - docker build -t benraa/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those immages and push them to docker hub
  - docker push benraa/multi-client
  - docker push benraa/multi-nginx
  - docker push benraa/multi-server
  - docker push benraa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucketname: "elasticbeanstalk-eu-central-1-484973702078"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

